model: deep_lab
backbone: resnet34
input_Channels: 4
num_classes: 9
scheme: supervised
data: full
optimizer: sgd
train_l_dir: './data/images_2021/train'
train_u_dir: './data/images_2024/train'
val_dir: './data/images_2021/val'
test_dir: './data/images_2021/test'
params:
  lr: 0.005
  weight_decay: 0.01
  momentum: 0.9
  
