model: deep_lab
# encoder: resnet34
encoder: efficientnet-b1
encoder_depth: 5
encoder_weights: imagenet # default=None
input_channels: 4
num_classes: 9
ssl: False
# train_l_dir: './data/dev_data/labeled/train'
# train_u_dir: './data/dev_data/unlabeled/train'
# val_dir: './data/dev_data/labeled/val'
# test_dir: './data/dev_data/labeled/test'

train_l_dir: './data/images_2021/train'
train_u_dir: './data/images_2024/train'
val_dir: './data/images_2021/val'
test_dir: './data/dev_data/labeled/test'
optimizer: sgd
device: 'cuda'
params:
  tau: .80 # high confidence tau for ssl (confidence threshold)
  batch_size: 2
  lr: 0.005
  weight_decay: 0.00001
  momentum: 0.99
  nesterov: True
  gamma: 0.999
  epochs: 20
  lam: 0 # Weight for unlabled loss in total loss calculation
  mu: 1 # Scaling factor for unlabled loss
  focal_loss: False
