model: deep_lab
# encoder: resnet34
encoder: resnet101
# encoder: efficientnet-b1
encoder_depth: 5
encoder_weights: imagenet # default=None
input_channels: 4
num_classes: 9
ssl: False

train_l_dir: './data/images_2021_reshuffled/train'
train_u_dir: './data/images_2024/train'
val_dir: './data/images_2021_reshuffled/val'
test_dir: './data/images_2021_reshuffled/test'
optimizer: adam
device: 'cuda'
params:
  tau: .80 # high confidence tau for ssl (confidence threshold)
  batch_size: 32
  lr: 0.005
  weight_decay: 0.0001
  momentum: 0.9
  nesterov: True
  gamma: 0.999
  epochs: 20
  lam: 0 # Weight for unlabled loss in total loss calculation
  mu: 1 # Scaling factor for unlabled loss
  focal_loss: False
